runtime: python39  # Specify the Python runtime version
entrypoint: gunicorn -b :$PORT app:app  # Define the entry point using Gunicorn

handlers:
  - url: /static
    static_dir: static  # Serve static files from the 'static' directory
  - url: /.*
    script: auto  # Route all other URLs to the application script